actors/urls.py
from django.urls import path
from . import views

app_name = 'actors'

urlpatterns = [
    path('', views.home, name='list-actors'),
    path('<int:id>/details', views.actor_details, name='actor_details'),
    path('<int:id>/update', views.actor_update, name='actor_update'),
    path('new/', views.actor_create, name='add_actor'),
    path('<int:id>/delete', views.delete_actor, name='actor-delete'),


]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='list-movies'),
    path('<int:id>/details',views.movie_details,name='movie_details' ),
    path('<int:id>/update',views.update_movie,name='movie-update' ),
    path('new/', views.create_movie, name='create_movie'),
    path('<int:id>/delete',views.delete_movie,name='movie-delete' ),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from project import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('actors/',include('actors.urls')),
    path('movies/',include('movies.urls')),
    path('',TemplateView.as_view(template_name="home.html"), name="home")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actors/models.py
from email.mime import image
from django.db import models
from django.forms import ImageField

# Create your models here.

GENDER=(
    ('FEMALE','Female'),
    ('MALE','Male'),
    ('OTHER','other')
)
class Actor(models.Model):
    name=models.CharField( max_length=50)
    gender=models.CharField(choices=GENDER, max_length=50)
    age=models.IntegerField(default=15)
    profile_picture = models.ImageField(upload_to='actors/') 

    def __str__(self):
        return self.name
    

movies/models.py
from django.db import models
from actors.models import Actor
# Create your models here.
class Movie(models.Model):
    name=models.CharField( max_length=50)
    production_year=models.PositiveSmallIntegerField(blank=True, null=True)
    image= models.ImageField(upload_to='movies/', default='img.png') 
    actors=models.ManyToManyField("actors.Actor",)
    created_at=models.DateField(  auto_now_add=True)
    updated_at=models.DateField( auto_now=True)

    def __str__(self):
        return self.name
    

actors/forms.py
from django import forms

from .models import Actor

class ActorForm(forms.ModelForm):

    class Meta:
        model = Actor
        fields = ('name','age','gender','profile_picture',)

movies/forms.py
from django import forms

from .models import Movie

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

actors/views.py
from django.shortcuts import render
from .models import Actor
from .forms import ActorForm
from django.shortcuts import redirect
from django.urls import reverse
from movies.models import Movie
# Create your views here.
def home(request):
    actors=Actor.objects.all()
    context={
        'actors':actors,
    }
    return render(request, 'actors/index.html',context)

def actor_details(request,id):
    actor=Actor.objects.get(id=id)
    
    movies=Movie.objects.filter(actors__id=id)
    print(movies)
    context={
        'actor':actor,
    }
    return render(request,'actors/actor_details.html',context)

def actor_create(request):
    if request.method == "POST":
        form = ActorForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            actor = form.save(commit=False)
            actor.save()
            return redirect(reverse('actors:actor_details', kwargs={'id' :actor.id}))

    else:
        form = ActorForm()
    return render(request, 'actors/add_actor.html', {'form': form})

def actor_update(request,id):
    actor=Actor.objects.get(id=id)
    
    if request.method == "POST":
        form = ActorForm(data=request.POST, files=request.FILES, instance=actor)
        if form.is_valid():
            actor = form.save(commit=False)
            actor.save()
            return redirect(reverse('actors:actor_details', kwargs={'id' :actor.id}))

    else:
        form = ActorForm(instance=actor)  
    
    return render(request, 'actors/actor_edit.html', {'form': form,'actor' :actor})

def delete_actor(request,id):
    actor=Actor.objects.get(id=id)
    actor.delete()
    return redirect(reverse('actors:list-actors'))

movies/views.py
from django.shortcuts import render
from .models import Movie
from django.shortcuts import redirect
from django.urls import reverse
from .forms import MovieForm

# Create your views here.
def index(request):
    movies=Movie.objects.all()
    context={
        'movies':movies,
    }
    return render(request, 'movies/index.html',context)

def movie_details(request,id):
    movie=Movie.objects.get(id=id)
    context={
        'movie':movie,
    }
    return render(request,'movies/movie_details.html',context)

def create_movie(request):
    if request.method == "POST":
        form = MovieForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.save()
            return redirect(reverse('movies:movie_details', kwargs={'id' :movie.id}))

    else:
        form = MovieForm()
    return render(request, 'movies/create_movie.html', {'form': form})


def update_movie(request,id):
    movie=Movie.objects.get(id=id)
    
    if request.method == "POST":
        form = MovieForm(data=request.POST, files=request.FILES, instance=movie)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.save()
            return redirect(reverse('movies:movie_details', kwargs={'id' :movie.id}))

    else:
        form = MovieForm(instance=movie)  
    
    return render(request, 'movies/movie_update.html', {'form': form,'movie' :movie})

def delete_movie(request,id):
    movie=Movie.objects.get(id=id)
    movie.delete()
    return redirect(reverse('movies:list-movies'))

templates/actors/actor_details.html
{% extends "../base.html" %}
{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <h1 class="my-4">
    {{actor.name}}
  </h1>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <img class="img-fluid" src="{{actor.profile_picture.url}}" alt="">
    </div>

    <div class="col-md-4">
      <h3 class="my-3">About {{actor.name}}</h3>
      <h5>age: {{actor.age}} years old 
        <br>
      {{actor.get_gender_display}} </h5>
      
  
    </div>


  </div>


</div>
<!-- /.container -->
{% endblock content %}

templates/actors/actor_edit.html
{% extends "../base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <h2>Update {{actor.name}} info</h2>
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <img width="200px" height="250px" src={{actor.profile_picture.url}} style="margin:15px" alt="">
    <br>
    <button type="submit" class="save btn btn-secondary">Save</button>
  </form>
</div>
{% endblock %}

templates/actors/add_actor.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    
    <div class="container">
        <h2>New Actor</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
</div>
{% endblock %}

templates/actors/index.html
{% extends "../base.html" %}
{% block title %} All actors{% endblock title %}
 {% block content %}
 <div class="row ">
  {% for actor in actors  %}
  <div class="col-md-2">
    <div class="card h-100">
      <img src="{{ actor.profile_picture.url }}" class="card-img-top h-100" alt="...">
      <div class="card-body">
        <h5 class="card-title">
          {{actor.name}}
        </h5>
        <p class="card-text">
          {{actor.get_gender_display}} <br>
          {{actor.age}} years old
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <a href="{% url 'actors:actor_details' actor.id %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
            <a href="{% url 'actors:actor_update' actor.id %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
            <a href="{% url 'actors:actor-delete' actor.id %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>

          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
 {% endblock content %}

templates/base.html
{% load static %}
<html>
<head>

    <title>
        {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="Album%20example%20for%20Bootstrap_files/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="Album%20example%20for%20Bootstrap_files/album.css" rel="stylesheet">

    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'actors:list-actors' %}">Actors</a>
              <a class="nav-link" href="{% url 'movies:list-movies' %}">Movies</a>
            
            </div>
          </div>
        </div>
      </nav>

      <main role="main">

        <section class="jumbotron text-center">
          <div class="container">
            <h1 class="jumbotron-heading">Movies and Actors</h1>

            <p class="lead text-muted">Simple page to display movies and actors built with django freamework</p>
          </div>
        </section>
  
        
  
      </main>
  

   {% block content %}{% endblock content %}
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "./base.html" %} 
{% block title %}  Home Page{% endblock title %}
 {% block content %}
<div class='container'>
 <a href="{%url 'movies:list-movies'%}" type="button" class="btn btn-primary btn-lg d-flex justify-content-cente">List All Movies</a>
 <br>
 <a href="{%url 'actors:list-actors'%}" type="button" class="btn btn-primary btn-lg d-flex justify-content-cente">List All Actors</a>
</diV>
{% endblock %}

templates/movies/create_movie.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    
    <div class="container">
        <h2>New Actor</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/index.html
{% extends "../base.html" %}
{% block title %} All actors{% endblock title %}
 {% block content %}
 <div class="row ">
  {% for movie in movies  %}
  <div class="col-md-2">
    <div class="card h-100">
      <img src="{{ movie.image.url }}" class="card-img-top h-100" alt="...">
      <div class="card-body">
        <h5 class="card-title">
          {{movie.name}}
        </h5>
        <p class="card-text">
        production year :  {{movie.production_year}} <br>
      
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <a href="{% url 'movies:movie_details' movie.id %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
            <a href="{% url 'movies:movie-update' movie.id %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
            <a href="{% url 'movies:movie-delete' movie.id %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>

          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
 {% endblock content %}

templates/movies/movie_details.html
{% extends "../base.html" %}
{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <h1 class="my-4">
    {{movie.name}}
  </h1>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <img class="img-fluid" src="{{movie.image.url}}" alt="">
    </div>

    <div class="col-md-4">
      <h3 class="my-3">About {{movie.name}}</h3>
      <h5>production year : {{movie.production_year}} 
        <br>
     </h5>
     <h3 class="my-3">Actors</h3>
     <ul>
       {% for actor in movie.actors.all  %}
      <a href="{% url 'actors:actor_details' actor.id%}"> <li> {{actor.name}} </li> </a>
       {% endfor %}
     </ul>
      
  
    </div>


  </div>
 
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock content %}

templates/movies/movie_update.html
{% extends "../base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <h2>Update {{movie.name}} info</h2>
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <img width="200px" height="250px" src={{movie.image.url}} style="margin:15px" alt="">
    <br>
    <button type="submit" class="save btn btn-secondary">Save</button>
  </form>
</div>
{% endblock %}